---
title: "R Notebook"
output: html_notebook
---
## Loading required libraries
```{r}
library(caret)
library(dummies)
library(plyr)
```
## Loading data
```{r}
train <- read.csv("noteBooks/Data/train.csv")

test <- read.csv("noteBooks/Data/test.csv")

```
## Cleaning Data
```{r}
panel <- rbind(train[,-ncol(train)],test) ## merging both test and subset of train

## deature variables

panel$year <- as.numeric(substr(as.character(panel$Open.Date),7,10))
panel$month <- as.numeric(substr(as.character(panel$Open.Date),1,2))
panel$day  <- as.numeric(substr(as.character(panel$Open.Date),4,5))

panel$Date <- as.Date(strptime(panel$Open.Date, "%m/%d/%Y"))


panel$days  <- as.numeric(Sys.Date()-panel$Date)

table(panel$City.Group)
panel$City.Group <- as.factor(panel$City.Group) ## Converting city groups as factors

table(panel$Type)
panel$Type[panel$Type == "DT"] <- "IL"
panel$Type[panel$Type == "MB"] <- "FC"
panel$Type <- as.factor(panel$Type)

panel <- subset(panel, select=-c(Open.Date,Date,City))

## converting some categorical variables int odummies

panel <- dummy.data.frame(panel, names=c("P14", "P15", "P16", "P17", "P18", "P19", "P20", "P21", "P22", "P23", "P24", "P25", "P30", "P31", "P32", "P33", "P34", "P35", "P36", "P37"), all=T)

ldf <- lapply(1:ncol(panel), function(k)
				{
					return(data.frame("column" = colnames(panel)[k],
									  "unique" = length(unique(panel[1:nrow(train),k]))))
				})

ldf <- ldply(ldf, data.frame)


# removing variables with unique valies
panel <- panel[,!names(panel) %in% ldf$column[ldf$unique == 1]]

# removing highly correlated variables
for (i in (6:ncol(panel)))
{
	panel[,i] <- as.numeric(panel[,i])
}

cor <- cor(panel[1:nrow(train),6:ncol(panel)])


high_cor <- findCorrelation(cor, cutoff = 0.99)

high_cor <- high_cor[high_cor != 186]

panel <- panel[,-c(high_cor+5)]


# splitting again into train and test

X_train <- panel[1:nrow(train),-1]
X_test <- panel[(nrow(train)+1):nrow(panel),]


#Building model on log of revenue

result <- log(train$revenue)
```
## Random Forest Modeling

```{r}
source("RandomForest.r")
model_rf_1 <- RandomForestRegression_CV(X_train,result,X_test,cv=5,ntree=25,nodesize=5,seed=235,metric="rmse")
model_rf_2 <- RandomForestRegression_CV(X_train,result,X_test,cv=5,ntree=25,nodesize=5,seed=235,metric="rmse")
model_rf_3 <- RandomForestRegression_CV(X_train,result,X_test,cv=5,ntree=25,nodesize=5,seed=235,metric="rmse")
model_rf_4 <- RandomForestRegression_CV(X_train,result,X_test,cv=5,ntree=25,nodesize=5,seed=235,metric="rmse")
model_rf_5 <- RandomForestRegression_CV(X_train,result,X_test,cv=5,ntree=25,nodesize=5,seed=235,metric="rmse")


test_rf_1 <- model_rf_1[[2]]
test_rf_2 <- model_rf_2[[2]]
test_rf_3 <- model_rf_3[[2]]
test_rf_4 <- model_rf_4[[2]]
test_rf_5 <- model_rf_5[[2]]


```

```{r}
submit <- data.frame("Id" = test_rf_1$Id,
					 "Prediction" = 0.2*exp(test_rf_1$pred_rf) + 0.2*exp(test_rf_2$pred_rf) + 0.2*exp(test_rf_3$pred_rf) + 0.2*exp(test_rf_4$pred_rf) + 0.2*exp(test_rf_5$pred_rf))
plot()
write.csv(submit, "submit.csv", row.names=F)


```


